/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData bag = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_arrow___down_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_arrow___right_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_edit = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_edit_square = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_heart = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_hide = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_category = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_message = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_profile = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_arrow___right_square = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_show = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_bold_star = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_light_3_user = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_3_user = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_document = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_shield_done = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_light_location = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_arrow___left = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_arrow___left_2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_arrow___right = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_arrow___right_2 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_arrow___right_circle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_bag = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_calendar = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_category = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_chat = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_close_square = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_delete = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_edit = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_filter = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_heart = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_home = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_location = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_lock = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_logout = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_message = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_notification = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_profile = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_send = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_square = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_show_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_star = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconly_regular_outline_show = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
